apiVersion: v1
kind: Service
metadata:
  name: api-docs-service
  namespace: quant-mumbai-api-docs
spec:
  selector:
    app: LABEL
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      name: tcp